# Generated by Django 2.2.6 on 2019-12-06 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_chaos_engineering.models
import django_chaos_engineering.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0011_update_proxy_permissions"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChaosKV",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=16, verbose_name="Key")),
                ("value", models.CharField(max_length=255, verbose_name="Value")),
                ("object_id", models.PositiveIntegerField()),
                (
                    "ctime",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation time"
                    ),
                ),
                (
                    "mtime",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Modification time"
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.ContentType",
                    ),
                ),
            ],
            options={
                "verbose_name": "ChaosKeyValue",
                "verbose_name_plural": "ChaosKeyValues",
                "ordering": ("key",),
            },
        ),
        migrations.CreateModel(
            name="ChaosActionResponse",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ctime",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation time"
                    ),
                ),
                (
                    "mtime",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Modification time"
                    ),
                ),
                (
                    "on_host",
                    models.CharField(
                        blank=True,
                        help_text="Limit the action to this host, blank for any",
                        max_length=255,
                        verbose_name="On host",
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="Enabled")),
                (
                    "probability",
                    django_chaos_engineering.models.RoundingDecimalField(
                        decimal_places=5,
                        default=100,
                        max_digits=8,
                        validators=[django_chaos_engineering.validators.validate_probability],
                    ),
                ),
                (
                    "verb",
                    models.CharField(
                        choices=[
                            ("slow", "slow"),
                            ("return", "return"),
                            ("raise", "raise"),
                        ],
                        help_text="Please refer to the documentation for configuration hints",
                        max_length=16,
                    ),
                ),
                (
                    "act_on_url_name",
                    models.CharField(
                        blank=True,
                        help_text="View name for response",
                        max_length=255,
                        null=True,
                        verbose_name="Act on url name",
                    ),
                ),
                ("for_groups", models.ManyToManyField(to="auth.Group")),
                ("for_users", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "ChaosActionResponse",
                "verbose_name_plural": "ChaosActionResponses",
                "ordering": ("-mtime",),
            },
        ),
        migrations.CreateModel(
            name="ChaosActionDB",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ctime",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation time"
                    ),
                ),
                (
                    "mtime",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Modification time"
                    ),
                ),
                (
                    "on_host",
                    models.CharField(
                        blank=True,
                        help_text="Limit the action to this host, blank for any",
                        max_length=255,
                        verbose_name="On host",
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="Enabled")),
                (
                    "probability",
                    django_chaos_engineering.models.RoundingDecimalField(
                        decimal_places=5,
                        default=100,
                        max_digits=8,
                        validators=[django_chaos_engineering.validators.validate_probability],
                    ),
                ),
                (
                    "verb",
                    models.CharField(
                        choices=[("slow", "slow"), ("raise", "raise")],
                        help_text="Please refer to the documentation for configuration hints",
                        max_length=16,
                    ),
                ),
                (
                    "act_on_attribute",
                    models.CharField(
                        choices=[
                            ("__name__", "Model name"),
                            ("__module__", "Model module name"),
                            ("_meta.app_label", "Model applicatin label"),
                            ("__class__.__name__", "Model parent class name"),
                        ],
                        help_text="Model attribute to act on",
                        max_length=255,
                        verbose_name="Act on attribute",
                    ),
                ),
                (
                    "act_on_value",
                    models.CharField(
                        blank=True,
                        help_text="Value of the attribute to act",
                        max_length=255,
                        verbose_name="Act on value",
                    ),
                ),
                ("for_groups", models.ManyToManyField(to="auth.Group")),
                ("for_users", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "ChaosActionDB",
                "verbose_name_plural": "ChaosActionDBs",
                "ordering": ("-mtime",),
            },
        ),
    ]
